### ISSUE TITLE
Export cardinality to LinkML

### ISSUE THREAD

**Issue by simoneguzzi** [AnacletoLAB/schemalink-webapp#56]
The relationship cardinality should be exported from the schema to the LinkML. It will be added to the `subject` and `object` of the `Relationship` class:

```yaml
FooToBarRelationship:
   slot_usage:
      subject:
         range: Foo
         minimum_cardinality: 0
         maximum_cardinality: 70
      object:
         range: Boo
         minimum_cardinality: 0
         maximum_cardinality: 10
```

Following these rules:

- If custom cardinalities are specified, use those.
- If one of the presets is selected:
   - `minimum_cardinality` is always 0.
   - `maximum_cardinality` is:
      - 1, for `1:x`/`x:1`.
      - absent for `N:x`/`x:N`.
